language: swift
before_install:
   - rvm use system
   - sudo gem install cocoapods
osx_image: xcode11
script: xcodebuild clean build test -workspace MobileWallet.xcworkspace -scheme MobileWallet -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.1,name=iPhone 8"