language: objective-c
osx_image: xcode11.2
xcode_workspace: MobileWallet.xcworkspace
xcode_scheme: MobileWallet
xcode_only_testing: MobileWalletTests
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 11
before_script:
- bash update_dependencies.sh